### ISSUE TITLE
Add Buildstream compatibility

### ISSUE THREAD

**Issue by Qinusty** [buildbarn/bb-remote-execution#22]
This issue will encompass the work required to bring Buildbarn into a state which it can work with Buildstream in accordance with the REAPI spec.

Buildbarn Issues:
- [x] #18: This needs to be resolved as it is not REAPI compliant and causes issues with clients which choose to use working directories other than the input root.
- [x] #20: This is likely required to allow `local_build_executor.go` to provide the input root as an output directory.
    - Alternatively, [bb-storage](https://github.com/buildbarn/bb-storage) could be altered to allow [local_directory](https://github.com/buildbarn/bb-storage/blob/master/pkg/filesystem/local_directory.go) to accept `"."` as a filepath component to `Lstat` to allow root to be selected for Lstat whilst the `outputParentDirectory` is root.
- [x] #23: This could be useful to allow clients to provide their own toolchains and avoid using toolchains provided by the runner.

Following the implementation of fixes for these two issues, I predict that Buildbarn should work with Buildstream as long as the runner executes the action with the input root as the root through some form of sandboxing.

**Comment by EdSchouten** [comment]
Is there still anything that needs to be done here?

**Comment by Qinusty** [comment]
All of the immediate issues mentioned in this tracking issue have been addressed.
